using System.Text;
using YamlDotNet.RepresentationModel;

namespace DataRepo.SchemaGen;

/// <summary>
/// Generates the C# table specifications from the LinkML schema, so the Parquet column names, order
/// and types are the schema's, never a second hand-written copy.
/// </summary>
/// <remarks>
/// The C# twin of <c>tools/build_tables.py</c>, with the same rules: <c>Bundle</c>'s attributes name the
/// tables, each one's range names the class whose attributes are the columns, an enum or class range is
/// a string (a foreign key or identifier, which DuckDB joins directly), a multivalued slot is a list,
/// and a column is nullable unless it is <c>required</c> or an <c>identifier</c>. A study layer
/// (<c>schema/study/*.yaml</c>) adds tables keyed on core identifiers and never alters a core table
/// (U5), so its tables are generated separately; the core's classes are merged in for range
/// resolution only.
/// </remarks>
public static class SchemaGenerator
{
    /// <summary>LinkML type to the generated <c>ColumnType</c> member.</summary>
    private static readonly Dictionary<string, string> ColumnTypes = new()
    {
        ["string"] = "String",
        ["uriorcurie"] = "String",
        ["uri"] = "String",
        ["integer"] = "Int64",
        ["float"] = "Float64",
        ["double"] = "Float64",
        ["decimal"] = "Float64",
        ["boolean"] = "Boolean",
        ["date"] = "Date",
        ["datetime"] = "TimestampUtc",
    };

    /// <summary>Render <c>Tables.g.cs</c> from the core schema and every study layer.</summary>
    /// <param name="schemaPath">The core LinkML schema, <c>schema/datarepo.yaml</c>.</param>
    /// <param name="studyDir">The study layers' folder, <c>schema/study</c>; may not exist.</param>
    /// <exception cref="InvalidDataException">A slot's range has no column type, or the schema lacks
    /// the <c>Bundle</c> class.</exception>
    public static string Render(string schemaPath, string studyDir)
    {
        var schema = Load(schemaPath);
        var classes = Map(schema, "classes");
        var enums = KeySet(Map(schema, "enums"));
        var layers = Directory.Exists(studyDir)
            ? Directory.GetFiles(studyDir, "*.yaml")
                .OrderBy(p => Path.GetFileNameWithoutExtension(p), StringComparer.Ordinal)
                .Select(p => (Name: Path.GetFileNameWithoutExtension(p), Doc: Load(p)))
                .ToList()
            : [];

        var sb = new StringBuilder();
        sb.Append("// GENERATED by DataRepo.SchemaGen from schema/datarepo.yaml and schema/study/*.yaml -- do not edit.\n");
        sb.Append("// Regenerate: dotnet run --project dotnet/src/DataRepo.SchemaGen\n");
        sb.Append("namespace DataRepo.Bundle;\n\n");
        sb.Append("public static partial class Tables\n{\n");
        sb.Append($"    /// <summary>The core schema's version.</summary>\n");
        sb.Append($"    public const string SchemaVersion = {Literal(Scalar(schema, "version"))};\n\n");
        sb.Append("    /// <summary>The core tables, in the schema's order.</summary>\n");
        sb.Append("    public static readonly IReadOnlyList<TableSpec> Core =\n    [\n");
        foreach (var (table, cls) in BundleTables(classes, "Bundle"))
            AppendTable(sb, table, cls, classes, KeySet(classes), enums, "        ");
        sb.Append("    ];\n\n");

        sb.Append("    /// <summary>Each study layer's version, by layer name.</summary>\n");
        sb.Append("    public static readonly IReadOnlyDictionary<string, string> StudyVersions = new Dictionary<string, string>\n    {\n");
        foreach (var (name, doc) in layers)
            sb.Append($"        [{Literal(name)}] = {Literal(Scalar(doc, "version"))},\n");
        sb.Append("    };\n\n");

        sb.Append("    /// <summary>Each study layer's tables, by layer name. Not part of <see cref=\"Core\"/>.</summary>\n");
        sb.Append("    public static readonly IReadOnlyDictionary<string, IReadOnlyList<TableSpec>> Study = new Dictionary<string, IReadOnlyList<TableSpec>>\n    {\n");
        foreach (var (name, doc) in layers)
        {
            var layerClasses = Map(doc, "classes");
            var merged = new Dictionary<string, YamlNode>(StringComparer.Ordinal);
            foreach (var (k, v) in classes) merged[k] = v;
            foreach (var (k, v) in layerClasses) merged[k] = v;
            var mergedEnums = new HashSet<string>(enums, StringComparer.Ordinal);
            mergedEnums.UnionWith(KeySet(Map(doc, "enums")));
            sb.Append($"        [{Literal(name)}] =\n        [\n");
            foreach (var (table, cls) in BundleTables(layerClasses, "StudyBundle"))
                AppendTable(sb, table, cls, merged, KeySet(merged), mergedEnums, "            ");
            sb.Append("        ],\n");
        }
        sb.Append("    };\n}\n");
        return sb.ToString();
    }

    /// <summary>Render <c>SchemaDocs.g.cs</c>: the schema's PROSE, for the MCP <c>describe</c> tool.</summary>
    /// <remarks>The C# twin of <c>render_docs</c> in <c>tools/build_tables.py</c>: table and column descriptions,
    /// ranges, enum names, identifier/multivalued/unit flags, and every enum's permissible values in the schema's
    /// own order. Types are NOT restated (they are in <c>Tables.g.cs</c>), and a slot's description on
    /// <c>Bundle</c>/<c>StudyBundle</c> is not carried, because every one reads "Rows of the &lt;table&gt; table."
    /// Descriptions are folded to one line as <c>" ".join(text.split())</c>.</remarks>
    public static string RenderDocs(string schemaPath, string studyDir)
    {
        var schema = Load(schemaPath);
        var classes = Map(schema, "classes");
        var enums = Map(schema, "enums");
        var layers = Directory.Exists(studyDir)
            ? Directory.GetFiles(studyDir, "*.yaml")
                .OrderBy(p => Path.GetFileNameWithoutExtension(p), StringComparer.Ordinal)
                .Select(p => (Name: Path.GetFileNameWithoutExtension(p), Doc: Load(p)))
                .ToList()
            : [];

        var sb = new StringBuilder();
        sb.Append("// GENERATED by DataRepo.SchemaGen from schema/datarepo.yaml and schema/study/*.yaml -- do not edit.\n");
        sb.Append("// Types are NOT here: they are in Tables.g.cs, generated from the same schema, and stating them twice\n");
        sb.Append("// is how a generated file starts lying.\n");
        sb.Append("#nullable enable\n");
        sb.Append("namespace DataRepo.Bundle;\n\n");
        sb.Append("public static partial class SchemaDocs\n{\n");
        sb.Append($"    public const string SchemaTitle = {Literal(Scalar(schema, "title") ?? Scalar(schema, "name"))};\n");
        sb.Append($"    public const string? SchemaDescription = {Literal(OneLine(Scalar(schema, "description")))};\n\n");
        sb.Append("    /// <summary>Permissible values of every enum the schema declares, in the schema's own order.</summary>\n");
        sb.Append("    public static readonly IReadOnlyDictionary<string, EnumDoc> Enums = new OrderedEnums\n    {\n");
        foreach (var (name, node) in enums) AppendEnum(sb, name, node, "        ");
        sb.Append("    };\n\n");
        sb.Append("    /// <summary>The core tables' documentation, in the schema's order.</summary>\n");
        sb.Append("    public static readonly IReadOnlyDictionary<string, TableDoc> Tables = new OrderedTables\n    {\n");
        foreach (var (table, cls) in BundleTables(classes, "Bundle"))
            AppendTableDoc(sb, table, cls, classes, enums, "        ");
        sb.Append("    };\n\n");
        sb.Append("    /// <summary>Each study layer's tables' documentation, by layer.</summary>\n");
        sb.Append("    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, TableDoc>> StudyTables = new Dictionary<string, IReadOnlyDictionary<string, TableDoc>>\n    {\n");
        foreach (var (name, doc) in layers)
        {
            var layerClasses = Map(doc, "classes");
            var merged = new Dictionary<string, YamlNode>(StringComparer.Ordinal);
            foreach (var (k, v) in classes) merged[k] = v;
            foreach (var (k, v) in layerClasses) merged[k] = v;
            var mergedEnums = new Dictionary<string, YamlNode>(StringComparer.Ordinal);
            foreach (var (k, v) in enums) mergedEnums[k] = v;
            foreach (var (k, v) in Map(doc, "enums")) mergedEnums[k] = v;
            sb.Append($"        [{Literal(name)}] = new OrderedTables\n        {{\n");
            foreach (var (table, cls) in BundleTables(layerClasses, "StudyBundle"))
                AppendTableDoc(sb, table, cls, merged, mergedEnums, "            ");
            sb.Append("        },\n");
        }
        sb.Append("    };\n\n");
        sb.Append("    /// <summary>Each study layer's own enums, by layer.</summary>\n");
        sb.Append("    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, EnumDoc>> StudyEnums = new Dictionary<string, IReadOnlyDictionary<string, EnumDoc>>\n    {\n");
        foreach (var (name, doc) in layers)
        {
            sb.Append($"        [{Literal(name)}] = new OrderedEnums\n        {{\n");
            foreach (var (enumName, node) in Map(doc, "enums")) AppendEnum(sb, enumName, node, "            ");
            sb.Append("        },\n");
        }
        sb.Append("    };\n}\n");
        return sb.ToString();
    }

    private static void AppendEnum(StringBuilder sb, string name, YamlNode node, string indent)
    {
        var values = Map(node, "permissible_values").Keys.Select(Literal);
        sb.Append($"{indent}[{Literal(name)}] = new EnumDoc({Literal(OneLine(Scalar(node, "description")))}, [{string.Join(", ", values)}]),\n");
    }

    private static void AppendTableDoc(StringBuilder sb, string table, string cls, IReadOnlyDictionary<string, YamlNode> classes,
        IReadOnlyDictionary<string, YamlNode> enums, string indent)
    {
        var classNode = classes[cls];
        sb.Append($"{indent}[{Literal(table)}] = new TableDoc({Literal(cls)}, {Literal(OneLine(Scalar(classNode, "description")))},\n{indent}[\n");
        foreach (var (name, attr) in Map(classNode, "attributes"))
        {
            var range = Scalar(attr, "range") ?? "string";
            sb.Append($"{indent}    new ColumnDoc({Literal(name)}, {Literal(OneLine(Scalar(attr, "description")))}, {Literal(range)}, ");
            sb.Append($"Enum: {(enums.ContainsKey(range) ? Literal(range) : "null")}, Identifier: {Bool(Flag(attr, "identifier"))}, ");
            sb.Append($"Multivalued: {Bool(Flag(attr, "multivalued"))}, Unit: {Literal(Scalar(attr, "unit"))}),\n");
        }
        sb.Append($"{indent}]),\n");
    }

    /// <summary>LinkML folds descriptions over several lines; a tool result wants one (Python's <c>" ".join(text.split())</c>).</summary>
    private static string? OneLine(string? text) =>
        string.IsNullOrEmpty(text) ? null : string.Join(" ", text.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));

    private static void AppendTable(
        StringBuilder sb, string table, string cls, IReadOnlyDictionary<string, YamlNode> classes,
        ISet<string> classNames, ISet<string> enums, string indent)
    {
        if (!classes.TryGetValue(cls, out var classNode))
            throw new InvalidDataException($"table {table}: no class named {cls}");
        sb.Append($"{indent}new TableSpec({Literal(table)}, {Literal(cls)},\n{indent}[\n");
        foreach (var (name, attr) in Map(classNode, "attributes"))
        {
            var range = Scalar(attr, "range") ?? "string";
            string type;
            if (classNames.Contains(range) || enums.Contains(range)) type = "String";
            else if (!ColumnTypes.TryGetValue(range, out type!))
                throw new InvalidDataException($"no column type for LinkML range '{range}' ({cls}.{name})");
            var isList = Flag(attr, "multivalued");
            var nullable = !Flag(attr, "required") && !Flag(attr, "identifier");
            sb.Append($"{indent}    new ColumnSpec({Literal(name)}, ColumnType.{type}, IsList: {Bool(isList)}, Nullable: {Bool(nullable)}),\n");
        }
        sb.Append($"{indent}]),\n");
    }

    private static IEnumerable<(string Table, string Class)> BundleTables(
        IReadOnlyDictionary<string, YamlNode> classes, string root)
    {
        if (!classes.TryGetValue(root, out var bundle))
            throw new InvalidDataException($"the schema has no {root} class");
        foreach (var (table, slot) in Map(bundle, "attributes"))
            yield return (table, Scalar(slot, "range") ?? throw new InvalidDataException($"{root}.{table} has no range"));
    }

    private static YamlNode Load(string path)
    {
        var stream = new YamlStream();
        using var reader = new StreamReader(path, Encoding.UTF8);
        stream.Load(reader);
        return stream.Documents[0].RootNode;
    }

    /// <summary>A mapping's children in document order; an absent or empty mapping is empty.</summary>
    private static IReadOnlyDictionary<string, YamlNode> Map(YamlNode? node, string key)
    {
        var result = new OrderedMap();
        if (node is YamlMappingNode m && m.Children.TryGetValue(new YamlScalarNode(key), out var child)
            && child is YamlMappingNode cm)
        {
            foreach (var (k, v) in cm.Children)
                result.Add(((YamlScalarNode)k).Value!, v);
        }
        return result;
    }

    private static string? Scalar(YamlNode? node, string key) =>
        node is YamlMappingNode m && m.Children.TryGetValue(new YamlScalarNode(key), out var v)
            && v is YamlScalarNode s ? s.Value : null;

    private static bool Flag(YamlNode? node, string key) =>
        string.Equals(Scalar(node, key), "true", StringComparison.OrdinalIgnoreCase);

    private static HashSet<string> KeySet(IReadOnlyDictionary<string, YamlNode> map) =>
        new(map.Keys, StringComparer.Ordinal);

    private static string Literal(string? s) =>
        s is null ? "null" : "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static string Bool(bool b) => b ? "true" : "false";

    /// <summary>A dictionary that enumerates in insertion order, as YAML mappings are read.</summary>
    private sealed class OrderedMap : IReadOnlyDictionary<string, YamlNode>
    {
        private readonly List<KeyValuePair<string, YamlNode>> _items = [];
        private readonly Dictionary<string, YamlNode> _index = new(StringComparer.Ordinal);

        public void Add(string key, YamlNode value)
        {
            _index.Add(key, value);
            _items.Add(new(key, value));
        }

        public YamlNode this[string key] => _index[key];
        public IEnumerable<string> Keys => _items.Select(i => i.Key);
        public IEnumerable<YamlNode> Values => _items.Select(i => i.Value);
        public int Count => _items.Count;
        public bool ContainsKey(string key) => _index.ContainsKey(key);
        public bool TryGetValue(string key, out YamlNode value) => _index.TryGetValue(key, out value!);
        public IEnumerator<KeyValuePair<string, YamlNode>> GetEnumerator() => _items.GetEnumerator();
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
    }
}
