<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DataRepo.Bundle\DataRepo.Bundle.csproj" />
    <ProjectReference Include="..\DataRepo.Ingest\DataRepo.Ingest.csproj" />
    <ProjectReference Include="..\DataRepo.Study\DataRepo.Study.csproj" />
    <ProjectReference Include="..\DataRepo.Site\DataRepo.Site.csproj" />
    <ProjectReference Include="..\DataRepo.Mcp\DataRepo.Mcp.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>datarepo</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
