using System.Text;
using System.Text.RegularExpressions;

namespace DataRepo.Site;

/// <summary>Compares two generated sites file by file, byte for byte, after normalising only what names the
/// generator itself (D41: the C# generator is a different program from the Python one, and says so).</summary>
/// <remarks>
/// Exactly two things are normalised, and nothing else:
/// <list type="number">
/// <item>the marker's <c>"generator": "datarepo &lt;version&gt;"</c> line;</item>
/// <item>every page's footer line <c>Generated by &lt;a href="..."&gt;datarepo&lt;/a&gt; &lt;version&gt; from catalog</c>.</item>
/// </list>
/// The generator writes no clock time of its own: every date on the site (<c>built_utc</c>, a bundle's
/// <c>written_utc</c>, Croissant's <c>datePublished</c>) is read from the catalog, so the same catalog gives
/// the same bytes.
/// </remarks>
public static class SiteParity
{
    private static readonly Regex MarkerGenerator = new("(\"generator\": \"datarepo )[^\"]*(\")");
    private static readonly Regex FooterVersion =
        new("(Generated by <a href=\"" + Regex.Escape(SiteGenerator.Repository) + "\">datarepo</a> )(.*?)( from catalog\n)");

    /// <summary>A file's bytes with the generator's own version replaced by a placeholder.</summary>
    public static byte[] Normalise(string relativePath, byte[] bytes)
    {
        var name = relativePath.Replace('\\', '/');
        if (name == SiteGenerator.SiteMarker)
            return Encoding.UTF8.GetBytes(MarkerGenerator.Replace(Encoding.UTF8.GetString(bytes), "${1}<version>${2}", 1));
        if (name.EndsWith(".html", StringComparison.Ordinal))
            return Encoding.UTF8.GetBytes(FooterVersion.Replace(Encoding.UTF8.GetString(bytes), "${1}<version>${3}", 1));
        return bytes;
    }

    /// <summary>Every file of both trees, relative, with <c>/</c>; <c>.git</c> is left out.</summary>
    public static SortedSet<string> Files(string root) =>
        new(Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories)
            .Select(f => Path.GetRelativePath(root, f).Replace('\\', '/'))
            .Where(f => !f.StartsWith(".git/", StringComparison.Ordinal)), StringComparer.Ordinal);

    /// <summary>The differences between two sites; empty when they are the same after normalisation.</summary>
    public static List<string> Compare(string expected, string actual, out int filesCompared, out long bytesCompared)
    {
        var differences = new List<string>();
        var left = Files(expected);
        var right = Files(actual);
        foreach (var f in left.Except(right)) differences.Add($"only in {expected}: {f}");
        foreach (var f in right.Except(left)) differences.Add($"only in {actual}: {f}");
        filesCompared = 0;
        bytesCompared = 0;
        foreach (var f in left.Intersect(right))
        {
            var a = Normalise(f, File.ReadAllBytes(Path.Combine(expected, f)));
            var b = Normalise(f, File.ReadAllBytes(Path.Combine(actual, f)));
            filesCompared++;
            bytesCompared += a.Length;
            if (a.AsSpan().SequenceEqual(b)) continue;
            var at = 0;
            while (at < a.Length && at < b.Length && a[at] == b[at]) at++;
            string Around(byte[] x) => Encoding.UTF8.GetString(x, Math.Max(0, at - 60), Math.Min(x.Length, at + 60) - Math.Max(0, at - 60))
                .Replace("\n", "\\n");
            differences.Add($"{f}: {a.Length} vs {b.Length} bytes, first difference at byte {at}\n" +
                            $"    expected ...{Around(a)}...\n    actual   ...{Around(b)}...");
        }
        return differences;
    }
}
