"""Generate docs/cli.md, the command reference, from the `datarepo` argument parser itself.

    python tools/build_cli_docs.py          # (re)write docs/cli.md
    python tools/build_cli_docs.py --check  # exit 1 if the page is stale

The parser is the single source of truth: every command, argument, default and help string on the
page is read from `datarepo.cli.build_parser()`, so the reference cannot describe a flag that does not
exist. `tests/test_cli_docs.py` fails on drift, in the CI job that installs the package.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from datarepo.cli import build_parser  # noqa: E402

OUT = ROOT / "docs" / "cli.md"

#: The order a reader meets the commands in, grouped by who runs them. Every command the parser has
#: must appear here exactly once; `render` refuses otherwise, so a new command cannot go undocumented.
GROUPS: list[tuple[str, str, list[str]]] = [
    (
        "Check the machine",
        "Run first on a new machine.",
        ["doctor"],
    ),
    (
        "Ingest: a producer's run becomes a bundle",
        "An instance operator runs these once per dataset, after the search. See "
        "[ingest.md](ingest.md) and [study.md](study.md).",
        ["manifest", "ingest", "inspect", "study", "run"],
    ),
    (
        "Build and publish: bundles become a catalog and a site",
        "`publish` is `build` then `site` in one step. See [build.md](build.md), [site.md](site.md) "
        "and [operating.md](operating.md).",
        ["publish", "build", "site", "catalog"],
    ),
    (
        "Ask: read a catalog",
        "See [querying.md](querying.md) and [mcp.md](mcp.md).",
        ["query", "mcp"],
    ),
]


def _subparsers(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    for action in parser._actions:  # noqa: SLF001 - argparse has no public accessor for this
        if isinstance(action, argparse._SubParsersAction):  # noqa: SLF001
            return dict(action.choices)
    raise SystemExit("datarepo's parser has no subcommands")


def _helps(parser: argparse.ArgumentParser) -> dict[str, str]:
    for action in parser._actions:  # noqa: SLF001
        if isinstance(action, argparse._SubParsersAction):  # noqa: SLF001
            return {a.dest: a.help or "" for a in action._choices_actions}  # noqa: SLF001
    return {}


def _cell(text: str) -> str:
    text = " ".join(text.split()).replace("|", "\\|")
    return text.replace("<", "&lt;").replace(">", "&gt;")


def _argument_rows(sub: argparse.ArgumentParser) -> list[str]:
    rows = []
    for action in sub._actions:  # noqa: SLF001
        if isinstance(action, argparse._HelpAction):  # noqa: SLF001
            continue
        if action.option_strings:
            name = ", ".join(f"`{o}`" for o in action.option_strings)
            if action.nargs != 0:
                name += f" `{action.metavar or action.dest.upper()}`"
        else:
            name = f"`{action.metavar or action.dest}`"
        if action.nargs in ("*", "+") or isinstance(action, argparse._AppendAction):  # noqa: SLF001
            name += " (repeatable)" if action.option_strings else " (one or more)" if action.nargs == "+" else " (zero or more)"
        required = "yes" if (action.required or (not action.option_strings and action.nargs not in ("*", "?"))) else ""
        help_text = action.help or ""
        if action.choices and not isinstance(action.choices, dict):
            help_text += f" One of: {', '.join(f'`{c}`' for c in action.choices)}."
        rows.append(f"| {name} | {required} | {_cell(help_text)} |")
    return rows


def render() -> str:
    parser = build_parser()
    subs = _subparsers(parser)
    helps = _helps(parser)
    listed = [name for _, _, names in GROUPS for name in names]
    missing = sorted(set(subs) - set(listed))
    extra = sorted(set(listed) - set(subs))
    if missing or extra or len(listed) != len(set(listed)):
        raise SystemExit(
            f"GROUPS in tools/build_cli_docs.py is out of step with the parser: "
            f"undocumented {missing}, unknown {extra}"
        )

    out = [
        "<!-- GENERATED by tools/build_cli_docs.py from datarepo.cli.build_parser(). "
        "Do not edit by hand. -->\n\n",
        "# Command reference\n\n",
        "Every `datarepo` command, with every argument it takes. This page is generated from the "
        "program's own argument parser, so it lists exactly what the installed version accepts; "
        "`datarepo <command> --help` prints the same text.\n\n",
        "New here? Start with [getting-started.md](getting-started.md), which runs the main "
        "commands end to end on the example instance shipped in this repository.\n\n",
        "| Command | What it does |\n|---|---|\n",
    ]
    for _, _, names in GROUPS:
        for name in names:
            out.append(f"| [`{name}`](#datarepo-{name}) | {_cell(helps.get(name, ''))} |\n")
    out.append(
        "\n`datarepo --version` prints the installed version.\n\n"
        "**Exit status.** `0` when the command did what it was asked, including a no-op it reports "
        "(an unchanged catalog, a delivery already written). `1` when it refused: a dataset the "
        "manifest excludes, a check that failed, a file that does not match its record. The reason "
        "is on standard error. `2` for a command line it cannot parse.\n"
    )
    for title, lede, names in GROUPS:
        out.append(f"\n## {title}\n\n{lede}\n")
        for name in names:
            sub = subs[name]
            usage = " ".join(sub.format_usage().split())
            usage = usage.removeprefix("usage: ")
            out.append(f"\n### `datarepo {name}`\n\n{_cell(helps.get(name, ''))[:1].upper()}"
                       f"{_cell(helps.get(name, ''))[1:]}.\n\n```\n{usage}\n```\n\n")
            rows = _argument_rows(sub)
            if rows:
                out.append("| Argument | Required | Meaning |\n|---|---|---|\n")
                out.append("\n".join(rows) + "\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if docs/cli.md is stale")
    args = ap.parse_args()
    text = render()
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("stale, run python tools/build_cli_docs.py: docs/cli.md")
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
