<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DataRepo.Bundle\DataRepo.Bundle.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="mzLib" Version="1.0.593" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
